// 自動生成 (scripts/build-mega-icons.mjs): メガシンカ JP名 → アイコンキー。アイコンは public/disp-mega/<キー>.png（64x64）。
// MEGA_FORMS: ベース種名 → そのメガ形態のJP名配列（リザードン→[(メガX),(メガY)]、メタグロス→[(メガ)]）。
export const MEGA_ICON = {
  "アブソル(メガ)": "Absol",
  "ウツボット(メガ)": "Victreebel",
  "エアームド(メガ)": "Skarmory",
  "エルレイド(メガ)": "Gallade",
  "エンブオー(メガ)": "Emboar",
  "オニゴーリ(メガ)": "Glalie",
  "オーダイル(メガ)": "Feraligatr",
  "カイリュー(メガ)": "Dragonite",
  "カイロス(メガ)": "Pinsir",
  "カエンジシ(メガ)": "Pyroar",
  "カメックス(メガ)": "Blastoise",
  "カラマネロ(メガ)": "Malamar",
  "ガブリアス(メガ)": "Garchomp",
  "ガメノデス(メガ)": "Barbaracle",
  "ガルーラ(メガ)": "Kangaskhan",
  "キラフロル(メガ)": "Glimmora",
  "ギャラドス(メガ)": "Gyarados",
  "クチート(メガ)": "Mawile",
  "ケケンカニ(メガ)": "Crabominable",
  "ゲッコウガ(メガ)": "Greninja",
  "ゲンガー(メガ)": "Gengar",
  "ゴルーグ(メガ)": "Golurk",
  "サメハダー(メガ)": "Sharpedo",
  "サーナイト(メガ)": "Gardevoir",
  "シビルドン(メガ)": "Eelektross",
  "シャンデラ(メガ)": "Chandelure",
  "ジジーロン(メガ)": "Drampa",
  "ジュカイン(メガ)": "Sceptile",
  "ジュペッタ(メガ)": "Banette",
  "スコヴィラン(メガ)": "Scovillain",
  "スターミー(メガ)": "Starmie",
  "スピアー(メガ)": "Beedrill",
  "ズルズキン(メガ)": "Scrafty",
  "タイレーツ(メガ)": "Falinks",
  "タブンネ(メガ)": "Audino",
  "チャーレム(メガ)": "Medicham",
  "チリーン(メガ)": "Chimecho",
  "チルタリス(メガ)": "Altaria",
  "デンリュウ(メガ)": "Ampharos",
  "ドラミドロ(メガ)": "Dragalge",
  "ドリュウズ(メガ)": "Excadrill",
  "ニャオニクス♀(メガ)": "Meowstic",
  "ニャオニクス♂(メガ)": "Meowstic",
  "ハガネール(メガ)": "Steelix",
  "ハッサム(メガ)": "Scizor",
  "バクーダ(メガ)": "Camerupt",
  "バシャーモ(メガ)": "Blaziken",
  "バンギラス(メガ)": "Tyranitar",
  "ピクシー(メガ)": "Clefable",
  "ピジョット(メガ)": "Pidgeot",
  "フシギバナ(メガ)": "Venusaur",
  "フラエッテ(メガ)": "Floette",
  "フーディン(メガ)": "Alakazam",
  "ブリガロン(メガ)": "Chesnaught",
  "プテラ(メガ)": "Aerodactyl",
  "ヘラクロス(メガ)": "Heracross",
  "ヘルガー(メガ)": "Houndoom",
  "ペンドラー(メガ)": "Scolipede",
  "ボスゴドラ(メガ)": "Aggron",
  "マフォクシー(メガ)": "Delphox",
  "ミミロップ(メガ)": "Lopunny",
  "ムクホーク(メガ)": "Staraptor",
  "メガニウム(メガ)": "Meganium",
  "メタグロス(メガ)": "Metagross",
  "ヤドラン(メガ)": "Slowbro",
  "ヤミラミ(メガ)": "Sableye",
  "ユキノオー(メガ)": "Abomasnow",
  "ユキメノコ(メガ)": "Froslass",
  "ライチュウ(メガX)": "Raichu_X",
  "ライチュウ(メガY)": "Raichu_Y",
  "ライボルト(メガ)": "Manectric",
  "ラグラージ(メガ)": "Swampert",
  "リザードン(メガX)": "Charizard_X",
  "リザードン(メガY)": "Charizard_Y",
  "ルカリオ(メガ)": "Lucario",
  "ルチャブル(メガ)": "Hawlucha",
};
export const megaIconPath = (name) => MEGA_ICON[name] ? `disp-mega/${MEGA_ICON[name]}.png` : null;
export const MEGA_FORMS = (() => {
  const m = {};
  for (const k of Object.keys(MEGA_ICON)) { const b = k.replace(/\(メガ[XY]?\)$/, ""); (m[b] = m[b] || []).push(k); }
  return m;
})();
